# Generated by Django 5.1.2 on 2024-10-15 06:11

import django.db.models.deletion
import imagekit.models.fields
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField()),
                ('original_images', models.ImageField(upload_to='original_images/')),
                ('resizes_images', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='resizes_images/', verbose_name='resizes_images')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menu', verbose_name='menu')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منو ها',
                'ordering': ['parent__name', 'name'],
            },
        ),
    ]
