# Generated by Django 5.1.2 on 2024-10-17 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='size',
            field=models.CharField(blank=True, choices=[('SMALL', 'کوچک'), ('LARGE', 'بزرگ')], max_length=50),
        ),
        migrations.AddField(
            model_name='menu',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
