# Generated by Django 5.1.2 on 2024-10-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_description_menu_size_menu_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='size',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='stock',
        ),
        migrations.AddField(
            model_name='menu',
            name='available',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
        migrations.AddField(
            model_name='menu',
            name='price_large',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت (بزرگ)'),
        ),
        migrations.AddField(
            model_name='menu',
            name='price_small',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت (کوچک)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='original_images',
            field=models.ImageField(blank=True, null=True, upload_to='original_images/'),
        ),
    ]
