# Generated by Django 5.1.2 on 2024-10-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menu_price_remove_menu_size_remove_menu_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menues'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='available',
            field=models.BooleanField(default=True, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price_large',
            field=models.IntegerField(blank=True, null=True, verbose_name='price (large)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price_small',
            field=models.IntegerField(blank=True, null=True, verbose_name='price (small)'),
        ),
    ]
