# Generated by Django 5.1.2 on 2024-10-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_remove_menu_price_remove_menu_size_remove_menu_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
