# Generated by Django 5.1.2 on 2024-10-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menu_price_remove_menu_size_remove_menu_stock_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ManyToManyField(related_name='orders', to='menu.menu', verbose_name='آیتم منو'),
        ),
    ]
